name: Check Update

on:
  schedule:
    - cron: '43 20 * * *'

jobs:
  check:
    name: Check Update
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run check-update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update packages data
          branch: create-pull-request/check-update
          delete-branch: true
          title: '[Update] Update packages data'
          body: |
            Update some packages data
          labels: enhancement
          assignees: hal-shu-sato
          reviewers: hal-shu-sato
